import { describe, it } from "node:test";
import assert from "node:assert/strict";
import * as sdk from "./index.js";

const EXPECTED_EXPORTS = [
  "ASSET_FIXTURES",
  "ASSET_AUCTION_SCHEMA_ID",
  "ASSET_AUCTION_SCHEMA_REF",
  "AssetConfigError",
  "CORE_V2_RECEIPT_VERSION",
  "KeeperStatusClient",
  "MAINNET_ARTIFACTS",
  "MAINNET_CONFIRM_PHRASE",
  "MAINNET_DEPLOY_MIN_XLM_STROOPS",
  "MAINNET_MICRO_MAX_ESCROW",
  "MAINNET_MIN_FEE_RESERVE_STROOPS",
  "MAX_APPLICATION_PAYLOAD_BYTES",
  "MAX_AUDITOR_BLOB_BYTES",
  "MAX_CIPHERTEXT_BYTES",
  "MAX_V2_PARTICIPANTS",
  "PAYLOAD_ENVELOPE_VERSION",
  "PAYLOAD_HEADER_BYTES",
  "PUBLISHED_AUCTION_EVIDENCE_VERSION",
  "QUICKNET_HASH",
  "RECEIPT_VERSION",
  "SEALED_PROPOSAL_SCHEMA_ID",
  "SEALED_PROPOSAL_SCHEMA_REF",
  "SUB_ROSA_DEPLOYMENTS",
  "RoundContract",
  "RoundErrors",
  "StatusApiError",
  "SubRosaClient",
  "SubRosaClientConfigError",
  "SubRosaMissingReturnValueError",
  "SubRosaNetworkMismatchError",
  "SubRosaPreflightError",
  "SubRosaSubmitError",
  "SubRosaTimeoutError",
  "SubRosaTransactionError",
  "assertMainnetConfirmed",
  "assertMicroAmounts",
  "assertReadinessForExecute",
  "assetAuctionRound",
  "auditorPublicKey",
  "chainInfo",
  "contractErrorCode",
  "contractExplorerUrl",
  "createOzChannelsSubmitter",
  "createOzChannelsSubmitterFromEnv",
  "createSacBalanceReader",
  "createAssetAuctionRound",
  "createSealedProposalRound",
  "currentRound",
  "decodePayloadEnvelope",
  "decodeSealedProposal",
  "defaultMainnetReadinessInput",
  "evaluatePreflight",
  "encodeSealedProposal",
  "encodePayloadEnvelope",
  "fetchContractWasmHash",
  "fetchKeeperStatus",
  "fetchRoundBeacon",
  "fetchRoundSignature",
  "formatReadinessReport",
  "generateAuditorKeypair",
  "generateNonce",
  "hasBlockingFailures",
  "nativeXlmSacId",
  "networkFingerprint",
  "normalizeRoundId",
  "normalizeSorobanContractId",
  "openIdentity",
  "openPayload",
  "parseReceipt",
  "parseReceiptV2",
  "parsePublishedAuctionEvidence",
  "payloadCommitment",
  "quicknet",
  "redactReceipt",
  "resolveSubRosaDeployment",
  "roundInSeconds",
  "runMainnetReadiness",
  "serializeReceipt",
  "serializeReceiptV2",
  "serializePublishedAuctionEvidence",
  "sealAssetBid",
  "sealIdentity",
  "sealPayload",
  "sealProposal",
  "sealedProposalRound",
  "tryDecodeBase64",
  "tryDecodeHex",
  "validateAssetConfig",
  "validateAssetConfigs",
  "validateEncryptedBlob",
  "validateContractNetwork",
  "isSubRosaNetwork",
  "transactionExplorerUrl",
  "verifyReceipt",
  "verifyReceiptV2",
  "verifyPublishedAuctionEvidence",
  "verifySettledRoundProof",
];

describe("SDK public API snapshot", () => {
  it("should match the expected named exports", () => {
    const actual = Object.keys(sdk).sort();
    const expected = [...EXPECTED_EXPORTS].sort();
    assert.deepEqual(actual, expected);
  });
});
